# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modelone.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Button_export = QtWidgets.QPushButton(self.centralwidget)
        self.Button_export.setGeometry(QtCore.QRect(50, 200, 81, 21))
        self.Button_export.setObjectName("Button_export")
        self.vpn_password = QtWidgets.QPushButton(self.centralwidget)
        self.vpn_password.setGeometry(QtCore.QRect(160, 200, 121, 21))
        self.vpn_password.setObjectName("vpn_password")
        self.vpn_username_2 = QtWidgets.QLabel(self.centralwidget)
        self.vpn_username_2.setGeometry(QtCore.QRect(50, 50, 81, 21))
        self.vpn_username_2.setObjectName("vpn_username_2")
        self.label_vpnp = QtWidgets.QLabel(self.centralwidget)
        self.label_vpnp.setGeometry(QtCore.QRect(50, 98, 81, 21))
        self.label_vpnp.setObjectName("label_vpnp")
        self.vu = QtWidgets.QLineEdit(self.centralwidget)
        self.vu.setGeometry(QtCore.QRect(130, 50, 113, 20))
        self.vu.setObjectName("vu")
        self.vp = QtWidgets.QLineEdit(self.centralwidget)
        self.vp.setGeometry(QtCore.QRect(130, 100, 113, 20))
        self.vp.setObjectName("vp")
        self.iu = QtWidgets.QLineEdit(self.centralwidget)
        self.iu.setGeometry(QtCore.QRect(410, 50, 113, 20))
        self.iu.setObjectName("iu")
        self.ip = QtWidgets.QLineEdit(self.centralwidget)
        self.ip.setGeometry(QtCore.QRect(410, 100, 113, 20))
        self.ip.setObjectName("ip")
        self.label_inciteu = QtWidgets.QLabel(self.centralwidget)
        self.label_inciteu.setGeometry(QtCore.QRect(310, 50, 101, 20))
        self.label_inciteu.setObjectName("label_inciteu")
        self.label_incitep = QtWidgets.QLabel(self.centralwidget)
        self.label_incitep.setGeometry(QtCore.QRect(310, 100, 101, 21))
        self.label_incitep.setObjectName("label_incitep")
        self.label_years = QtWidgets.QLabel(self.centralwidget)
        self.label_years.setGeometry(QtCore.QRect(50, 136, 81, 16))
        self.label_years.setObjectName("label_years")
        self.label_yeare = QtWidgets.QLabel(self.centralwidget)
        self.label_yeare.setGeometry(QtCore.QRect(50, 159, 81, 20))
        self.label_yeare.setObjectName("label_yeare")
        self.label_oz = QtWidgets.QLabel(self.centralwidget)
        self.label_oz.setGeometry(QtCore.QRect(210, 125, 91, 31))
        self.label_oz.setObjectName("label_oz")
        self.label_dt = QtWidgets.QLabel(self.centralwidget)
        self.label_dt.setGeometry(QtCore.QRect(210, 160, 91, 16))
        self.label_dt.setObjectName("label_dt")
        self.label_ra = QtWidgets.QLabel(self.centralwidget)
        self.label_ra.setGeometry(QtCore.QRect(430, 130, 111, 16))
        self.label_ra.setObjectName("label_ra")
        self.dt = QtWidgets.QComboBox(self.centralwidget)
        self.dt.setGeometry(QtCore.QRect(300, 160, 111, 22))
        self.dt.setObjectName("dt")
        self.dt.addItem("")
        self.year_start = QtWidgets.QComboBox(self.centralwidget)
        self.year_start.setGeometry(QtCore.QRect(140, 130, 60, 22))
        self.year_start.setObjectName("year_start")
        self.year_start.addItem("")
        self.year_start.addItem("")
        self.year_start.addItem("")
        self.year_start.addItem("")
        self.year_start.addItem("")
        self.year_start.addItem("")
        self.year_end = QtWidgets.QComboBox(self.centralwidget)
        self.year_end.setGeometry(QtCore.QRect(140, 160, 60, 22))
        self.year_end.setObjectName("year_end")
        self.year_end.addItem("")
        self.year_end.addItem("")
        self.year_end.addItem("")
        self.year_end.addItem("")
        self.year_end.addItem("")
        self.year_end.addItem("")
        self.on = QtWidgets.QLineEdit(self.centralwidget)
        self.on.setGeometry(QtCore.QRect(300, 130, 113, 20))
        self.on.setObjectName("on")
        self.research_area = QtWidgets.QComboBox(self.centralwidget)
        self.research_area.setGeometry(QtCore.QRect(440, 160, 60, 22))
        self.research_area.setObjectName("research_area")
        self.research_area.addItem("")
        self.research_area.addItem("")
        self.Button_3 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_3.setGeometry(QtCore.QRect(320, 200, 81, 20))
        self.Button_3.setObjectName("Button_3")
        self.Button_4 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_4.setGeometry(QtCore.QRect(440, 200, 56, 21))
        self.Button_4.setObjectName("Button_4")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(50, 261, 371, 131))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        self.Button_export.clicked.connect(MainWindow.export_test)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button_export.setText(_translate("MainWindow", "导出初始表"))
        self.vpn_password.setText(_translate("MainWindow", "计算被引频次"))
        self.vpn_username_2.setText(_translate("MainWindow", "vpn_username"))
        self.label_vpnp.setText(_translate("MainWindow", "vpn_password"))
        self.label_inciteu.setText(_translate("MainWindow", "incite_username"))
        self.label_incitep.setText(_translate("MainWindow", "incite_password"))
        self.label_years.setText(_translate("MainWindow", "year_start"))
        self.label_yeare.setText(_translate("MainWindow", "year_end"))
        self.label_oz.setText(_translate("MainWindow", "orignize name"))
        self.label_dt.setText(_translate("MainWindow", "document type"))
        self.label_ra.setText(_translate("MainWindow", "research area"))
        self.dt.setItemText(0, _translate("MainWindow", "***"))
        self.year_start.setItemText(0, _translate("MainWindow", "1980"))
        self.year_start.setItemText(1, _translate("MainWindow", "1990"))
        self.year_start.setItemText(2, _translate("MainWindow", "2000"))
        self.year_start.setItemText(3, _translate("MainWindow", "2010"))
        self.year_start.setItemText(4, _translate("MainWindow", "2015"))
        self.year_start.setItemText(5, _translate("MainWindow", "2020"))
        self.year_end.setItemText(0, _translate("MainWindow", "1980"))
        self.year_end.setItemText(1, _translate("MainWindow", "1990"))
        self.year_end.setItemText(2, _translate("MainWindow", "2000"))
        self.year_end.setItemText(3, _translate("MainWindow", "2010"))
        self.year_end.setItemText(4, _translate("MainWindow", "2015"))
        self.year_end.setItemText(5, _translate("MainWindow", "2020"))
        self.research_area.setItemText(0, _translate("MainWindow", "New Item"))
        self.research_area.setItemText(1, _translate("MainWindow", "New Item"))
        self.Button_3.setText(_translate("MainWindow", "计算接近度"))
        self.Button_4.setText(_translate("MainWindow", "制图"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
